"""Prompts. Short and imperative — a 4B model degrades fast on long instructions."""

from __future__ import annotations

from frus_agentic_rag.retrieval.models import Evidence

PLANNER_SYSTEM = """You plan retrieval over Foreign Relations of the United States (FRUS), \
a closed corpus of declassified US diplomatic documents. You never answer from memory.

Pick exactly one route:
- lookup: asks for one specific named document or volume.
- simple: one factual question answerable from one retrieval.
- timeline: asks for a sequence or "when" over a date range.
- complex: needs comparison, causation, or two or more distinct facts.
- status: asks whether a volume/period is published or planned.

Rules:
- Any factual or historical question needs retrieval. Only greetings and questions \
about how to use this system may set needs_retrieval=false.
- Write subqueries in ENGLISH; the corpus is English. Write at most 3.
- simple/lookup/status: exactly 1 subquery. timeline: 1-2. complex: 2-3.
- Put date constraints in date_from/date_to as yyyy-mm-dd, not in the query text.
- answer_language is the language of the user's question: zh-TW or en.
- required_evidence lists what must be shown for an answer to stand."""


def planner_user(question: str) -> str:
    return f"User question:\n{question}\n\nReturn the plan as JSON."


GRADER_SYSTEM = """You judge whether retrieved FRUS passages cover what a question needs.

You are NOT a historian here. Do not add facts. Do not guess. Judge coverage only.

For each hop:
- supported: the accepted passages state the needed fact directly.
- partial: related but the specific fact is missing.
- unsupported: nothing relevant.

accepted_evidence_ids must be copied verbatim from the EVIDENCE ids shown. \
Never invent an id.

If a hop is partial or unsupported, give corrective_query: ONE short English \
retrieval query, under 20 words, that would find the missing fact. Do not explain \
your reasoning anywhere in the JSON — only the fields, and keep them terse."""


# Qwen3 4B at num_ctx 8192 degrades — and then read-times-out — well before the
# window is full. These caps keep the grader prompt near 2k tokens.
GRADER_MAX_EVIDENCE = 6
GRADER_EVIDENCE_CHARS = 700
SYNTH_MAX_EVIDENCE = 8
SYNTH_EVIDENCE_CHARS = 1100


def _fmt_evidence(evidence: list[Evidence], max_chars: int = 1200) -> str:
    lines = []
    for e in evidence:
        body = e.text[:max_chars]
        lines.append(
            f"[id: {e.evidence_id}] ({e.volume_id} Doc.{e.doc_number} {e.date_from})\n"
            f"{e.head}\n{body}"
        )
    return "\n\n---\n\n".join(lines) if lines else "(no evidence retrieved)"


def grader_user(question: str, hops: list[str], evidence: list[Evidence]) -> str:
    hop_list = "\n".join(f"- {h}" for h in hops) or "- (single hop) answer the question"
    return (
        f"QUESTION:\n{question}\n\nHOPS TO COVER:\n{hop_list}\n\n"
        f"EVIDENCE:\n{_fmt_evidence(evidence[:GRADER_MAX_EVIDENCE], GRADER_EVIDENCE_CHARS)}\n\n"
        "Return the grade as JSON."
    )


SYNTH_SYSTEM_ZH = """你依據 FRUS 原始文件回答，並且只能使用下面提供的 EVIDENCE。

規則：
- 每個主張都要附上使用到的 evidence id，id 必須逐字複製，不可自創。
- EVIDENCE 沒說的就不要說。不要補充你自己知道的歷史。
- 文件互相衝突時並列陳述，不要替史家下定論。
- 用繁體中文（台灣）作答。人名、機構、文件標題後面附英文原文。
- answer_text 不要放網址；引用區塊由程式產生。
- limitations 說明證據沒有涵蓋到什麼。"""

SYNTH_SYSTEM_EN = """You answer from FRUS primary documents using ONLY the EVIDENCE below.

Rules:
- Every claim carries the evidence ids it rests on, copied verbatim. Never invent an id.
- If the EVIDENCE does not say it, do not say it. Do not add outside history.
- Where documents conflict, present both; do not adjudicate.
- Do not put URLs in answer_text; the citation block is generated by code.
- limitations states what the evidence does not cover."""


def synth_user(question: str, evidence: list[Evidence]) -> str:
    body = _fmt_evidence(evidence[:SYNTH_MAX_EVIDENCE], SYNTH_EVIDENCE_CHARS)
    return (
        f"QUESTION:\n{question}\n\nEVIDENCE:\n{body}\n\n"
        "Return the answer as JSON. claims must not be empty: every sentence of "
        "answer_text has to be backed by at least one claim carrying evidence ids "
        "copied verbatim from the ids above."
    )


ABSTAIN_ZH = (
    "根據目前檢索到的 FRUS 文件，無法支持一個有憑據的回答。"
    "FRUS 只收錄已出版卷次的解密外交文件；"
    "若該主題屬於尚未出版的卷次，或用詞與檔案不符，就會檢索不到。"
)
ABSTAIN_EN = (
    "The retrieved FRUS documents do not support a grounded answer. "
    "FRUS covers only published volumes of declassified US diplomatic records; "
    "a topic in an unpublished volume, or phrased unlike the archival wording, will not be found."
)
